export const ImagesActionTypes = {
    FETCH_IMAGES_START: 'FETCH_IMAGES_START',
    FETCH_IMAGES_SUCCESS: 'FETCH_IMAGES_SUCCESS',
    FETCH_IMAGES_FAILURE: 'FETCH_IMAGES_FAILURE',
    SWITCH_GENDER_START: 'SWITCH_GENDER_START',
    SWITCH_GENDER_SUCCESS: 'SWITCH_GENDER_SUCCESS',
    SWITCH_GENDER_FAILURE: 'SWITCH_GENDER_FAILURE',
}




